### ISSUE TITLE
[BUGS] Penempatan Karyawan

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#15]
@ad3n 
Menu > Karyawan > Penempatan Karyawan

![screenshot from 2017-11-16 17-21-30](https://user-images.githubusercontent.com/33483011/32886304-da2c1f60-caf2-11e7-85d4-3e7e3bd0ea1b.png)

klik simpan hasilnya seperti ini

![screenshot from 2017-11-16 17-21-46](https://user-images.githubusercontent.com/33483011/32886318-e664e442-caf2-11e7-8ea1-109e8d912f71.png)

**Comment by ad3n** [comment]
@j1top : sudah ok kah dengan commit itu?

**Comment by ad3n** [comment]
@j1top bagaimana pak sudah ok kah?

**Comment by j1top** [comment]
belum test gan @ad3n  ini lg upgrade dari mysql ke postgres

**Comment by ad3n** [comment]
hahaha ok pak siap... oiya, di karyawan juga saya tambah field baru... jadi memang harus restore db... Kalau bapak bisa bantu, tolong baru bikin dummy data di folder data itu sudah ada semua tinggal dilengkapi aja terutama pada kode-kode yang predefine di .env.dist

**Comment by j1top** [comment]
BUGS FIXED, THANKS GAN @ad3n
