### ISSUE TITLE
[BUGS] RIWAYAT PENGGAJIAN

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#16]
bugs nya seperti ini

![screenshot from 2017-11-18 01-55-12](https://user-images.githubusercontent.com/33483011/32963780-a2f576c4-cc03-11e7-82a0-2b1b460a0d10.png)

**Comment by ad3n** [comment]
@j1top : ini pas ngapain ya? buka menu kah? bisa coba pull terakhir?

**Comment by ad3n** [comment]
bisa minta tolong versi PHP dan cara dapetin errornya pak?

**Comment by j1top** [comment]
@ad3n 
`PHP 7.1.11`

done with last pull

**Comment by ad3n** [comment]
ok noted :-D kirain masih hehehe

**Comment by j1top** [comment]
setelah git pull terakhir ada error lagi di

penggajian > riwayat penggajian

![screenshot from 2017-11-18 17-59-39](https://user-images.githubusercontent.com/33483011/32979589-83e3a076-cc8a-11e7-9b2f-3f1c32fc91b8.png)

**Comment by ad3n** [comment]
ok noted...

**Comment by ad3n** [comment]
@j1top apakah sudah ok?

**Comment by j1top** [comment]
ok... fixed
