### ISSUE TITLE
[BUGS] Tambah Kontrak/Surat Keputusan

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#23]
PROSES

![screenshot from 2017-11-19 19-41-33](https://user-images.githubusercontent.com/33483011/32990787-008ef53a-cd62-11e7-8330-1093dd4f6632.png)

ERROR

![screenshot from 2017-11-19 19-42-25](https://user-images.githubusercontent.com/33483011/32990791-1648aca4-cd62-11e7-8577-4b91caa07e7b.png)

**Comment by ad3n** [comment]
Ok noted

**Comment by ad3n** [comment]
@j1top : monggo pak dicek lagi

**Comment by j1top** [comment]
ok, fixed
