### ISSUE TITLE
[BUGS] Konfigurasi

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#24]
sebelumnya bisa, tapi setelah beberapa commit jd ada bugs di edit nama konfigurasi

![screenshot from 2017-11-19 21-38-56](https://user-images.githubusercontent.com/33483011/32991667-4ad5db30-cd72-11e7-8efe-50a779db1f01.png)

![screenshot from 2017-11-19 21-39-14](https://user-images.githubusercontent.com/33483011/32991669-54a39f80-cd72-11e7-9236-745bd9af4a46.png)

**Comment by ad3n** [comment]
Hhhmmm ok noted dulu Pak... Hari ini insya Allah tak selesaikan

**Comment by ad3n** [comment]
Kayaknya karena ada config yang array... Yaitu hari libur

**Comment by ad3n** [comment]
@j1top : monggo pak dicek lagi

**Comment by j1top** [comment]
done
