### ISSUE TITLE
[Req] Tambah Kecamatan

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#26]
@ad3n bisa tambah kolom kecamatan ga di alamat ?

**Comment by ad3n** [comment]
Bisa provide datanya ga Pak? Kalau boleh sampai data Desa

**Comment by j1top** [comment]
bisa deh :grin:

**Comment by ad3n** [comment]
Ok Pak nanti saya siapkan

**Comment by ad3n** [comment]
@j1top : bisa minta tolong untuk melengkapi data Propinsi dan Kabupaten/Kota dulu ga pak? Biar saya siapkan untuk Kecamatan sampai Desanya...

Hanya saja nanti ga mandatory untuk di formnya :-)

**Comment by j1top** [comment]
Provinsi dan kabupaten kota sudah lengkap gan @a3den

**Comment by ad3n** [comment]
ooo hahaha iya ternyata
