### ISSUE TITLE
[BUGS] Perubahan Pajak

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#27]
Menu => Karyawan => Perubahaan Pajak showing error like this

![screenshot from 2017-11-22 15-43-01](https://user-images.githubusercontent.com/33483011/33117709-0dcf3b06-cf9c-11e7-8cd8-02f0661b6c4e.png)

**Comment by ad3n** [comment]
Schema update dulu Pak

**Comment by j1top** [comment]
ok.. fixed :blush:
