### ISSUE TITLE
[BUGS] Setting Gaji

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#28]
Tidak ada komponen gaji dalam menu setting gaji

![screenshot from 2017-11-26 06-15-08](https://user-images.githubusercontent.com/33483011/33235718-2d860c18-d271-11e7-9741-65bcafb11db3.png)

**Comment by ad3n** [comment]
Tinggal ditambah pak di komponen gaji dengan tipe tunjangan tetap

**Comment by ad3n** [comment]
@j1top, yang ini gimana ya?

**Comment by ad3n** [comment]
@j1top bagaimana perkembangan yang ini ya?
