### ISSUE TITLE
[BUGS] TUNJANGAN BPJS JHT

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#29]
@ad3n jika perusahaan tidak memberikan tunjangan BPJS JHT tampil error seperti ini

![screenshot from 2017-11-26 17-12-09](https://user-images.githubusercontent.com/33483011/33239097-c5b540a6-d2cd-11e7-904b-a16e8dbbff09.png)

**Comment by ad3n** [comment]
Noted

**Comment by ad3n** [comment]
@j1top monggo pak dicek lagi

**Comment by j1top** [comment]
baru online gan @ad3n 
error baru

![screenshot from 2017-11-27 19-43-00](https://user-images.githubusercontent.com/33483011/33267253-5af18cfa-d3ab-11e7-9a27-072c3b7fb0eb.png)

**Comment by ad3n** [comment]
cek pak
