### ISSUE TITLE
No route found for "GET /" error

### ISSUE THREAD

**Issue by nafiesl** [KejawenLab/SemartHris#3]
Setelah sukses install SemartHris, dan `make serve`, saya mendapatkan error `No route found for "GET /"`, sepertinya belum ada route/controller action untuk melayani url `"/"`.

![selection_141](https://user-images.githubusercontent.com/8721551/32254231-64a43206-beda-11e7-888f-7a1ba7ac771e.jpg)

Saya temukan solusi dengan menambahkan route annotation untuk melayani url `"/"`. Pada class controller `KejawenLab\Application\SemartHris\Controller\Front\SecurityController`

![selection_142](https://user-images.githubusercontent.com/8721551/32254261-9706ce20-beda-11e7-98f5-0f2962831f59.jpg)

Terima kasih.

**Comment by ad3n** [comment]
@nafiesl : memang untuk URLnya menggunakan `/admin` untuk halaman Admin dan `/api` untuk halaman API :-)

Dan halaman / memang masih kosong dan itu tidak masalah karena itu bisa sangat mudah :-)
