### ISSUE TITLE
Merge Commit TaxGroupHistoryController

### ISSUE THREAD

**Issue by picobug** [KejawenLab/SemartHris#30]
Om, sepertinya ada merge commit yang belum resolve di file TaxGroupHistoryController

![127 0 0 1_8000_ ipad](https://user-images.githubusercontent.com/4065455/33290845-955ac24e-d3f6-11e7-8ff9-799dd7d4c1ad.png)

**Comment by j1top** [comment]
same as #29

**Comment by ad3n** [comment]
@picobug done

**Comment by ad3n** [comment]
maaf conflict file ternyata ke merge...

**Comment by picobug** [comment]
Udah sip gan (y)
