### ISSUE TITLE
[INFO] Download Template Absen Error

### ISSUE THREAD

**Issue by picobug** [KejawenLab/SemartHris#31]
Om, sekedar info sama dengan issue #9, tapi beda errornya di fungsi getFileSize return bukan string. Apakah env berpengaruh ya ?
![bug_001](https://user-images.githubusercontent.com/4065455/33299578-d83da004-d41e-11e7-8463-143d12167bfc.png)

**Comment by ad3n** [comment]
@picobug cek lagi ya gan

**Comment by picobug** [comment]
udah ok gan

**Comment by ad3n** [comment]
:+1:
