### ISSUE TITLE
[BUG] Button Submit Not Show When Using Autocomplete Type

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#4]
Dear @ad3n 

Tombol Simpan tidak tampil saat menggunakan autocomplete

![screenshot from 2017-11-07 06-29-15](https://user-images.githubusercontent.com/33483011/32546385-7efd89d6-c4b1-11e7-90ee-a337ed6407f4.png)

**Comment by ad3n** [comment]
@https://github.com/javiereguiluz/EasyAdminBundle/issues/1913

Tracked

**Comment by ad3n** [comment]
Saya close karena issue ada disebelah ya dan udah fix
