### ISSUE TITLE
Error Saat Menambahkan Alamat Perusahaan

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#5]
gan @ad3n 

saya menadpatkan error dibawah ini ketika menyimpan alamat perusahaan
![screenshot from 2017-11-10 00-10-14](https://user-images.githubusercontent.com/33483011/32618948-be62bef2-c5ab-11e7-8885-ebe86714ab20.png)

**Comment by ad3n** [comment]
Noted

**Comment by ad3n** [comment]
@j1top : Kalau boleh tau, apakah bapak punya address yang tidak memiliki ```Company```?

**Comment by ad3n** [comment]
@j1top : apakah sudah bisa dengan #https://github.com/KejawenLab/SemartHris/commit/cbbc2788dac007ee73487b2bda4fb7998cc7a21d ini?

**Comment by j1top** [comment]
error nya pindah gan @ad3n 
![screenshot from 2017-11-10 11-33-22](https://user-images.githubusercontent.com/33483011/32643120-bdd41c00-c60b-11e7-83e2-2e209426064d.png)

**Comment by ad3n** [comment]
Ok noted

**Comment by ad3n** [comment]
@j1top : kalau boleh tau, bagaimana inputannya?

**Comment by j1top** [comment]
@ad3n Nanti sy update gan, lg ga pegang laptop

**Comment by ad3n** [comment]
ok

**Comment by j1top** [comment]
@ad3n 
inputnya seperti ini
![screenshot from 2017-11-10 17-20-55](https://user-images.githubusercontent.com/33483011/32653908-f82779b2-c63b-11e7-8baa-ed4cb35a62de.png)

**Comment by j1top** [comment]
error baru setelah update repo seperti ini
![screenshot from 2017-11-10 17-27-28](https://user-images.githubusercontent.com/33483011/32654050-7d5408b2-c63c-11e7-871a-399549e6e6d1.png)

**Comment by ad3n** [comment]
Itu ketika save error kah?

**Comment by j1top** [comment]
ya gan

**Comment by j1top** [comment]
kalau di cek dari debug nya seperti ini errornya gan @ad3n 

![screenshot from 2017-11-10 20-33-49](https://user-images.githubusercontent.com/33483011/32660727-8db8d394-c656-11e7-8358-c08c2361337d.png)

**Comment by ad3n** [comment]
@j1top: itu njenengan milih company dulu atau ga?

**Comment by ad3n** [comment]
Oiya sekalian schema update ```php bin/console doctrine:schema:update --force``` untuk sync dengan DB terbaru

**Comment by ad3n** [comment]
@j1top : ok catched... itu error karena njenengan add alamat perusahaan tidak melalui menu perusahaan... ok saya akan coba fixing

**Comment by j1top** [comment]
Duplicate of #

**Comment by ad3n** [comment]
@j1top : by default, untuk nambah alamat perusahaan, njenengan harusnya via menu perusahaan tapi njenengan juga bisa by pass langsung... Nah itu bug ketika njenengan langsung by pass langsung karena transformer tetap bekerja mengkonversi inputan company njenengan padahal harusnya tidak perlu...

Jadi sekarang mohon dicoba lagi untuk memastikan, apakah commit itu sudah menyelesaikan
