### ISSUE TITLE
Script make cache-warmup returned with error code 2

### ISSUE THREAD

**Issue by agungid** [KejawenLab/SemartHris#6]
Assalamualaikum Wr.Wb.
Saya melakukan instalasi SemartHris.
Saat melakuan  `composer update --prefer-dist -vvv`  terdapat error seperti pada ss
![smarthris](https://user-images.githubusercontent.com/11351024/32642021-1fd005f2-c604-11e7-9fe2-dcc41b2d3451.png)

**Comment by ad3n** [comment]
@agungid: Wa'alaikum salam warohmatullah... Anda perlu install extension dom di PHPnya :-) saya akan tambahkan di readme berarti :-D
