### ISSUE TITLE
[BUGS] Tambah Jadwal Kerja

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#7]
@ad3n saya coba input jadwal shit kerja seperti ini

![screenshot from 2017-11-10 17-43-16](https://user-images.githubusercontent.com/33483011/32655170-26e97446-c63f-11e7-98ae-c9abe6a2f2ca.png)

saat di simpan hasilnya seperti ini

![screenshot from 2017-11-10 17-42-25](https://user-images.githubusercontent.com/33483011/32655194-358dfed6-c63f-11e7-97aa-2af572f05316.png)

**Comment by ad3n** [comment]
Ok noted

**Comment by ad3n** [comment]
@j1top : monggo dicek lagi apakah commit itu udah menyelesaikan masalah anda :-D
