### ISSUE TITLE
[BUGS] Tambah Alamat Karyawan

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#8]
Gan @ad3n 
saat membuka alamat karyawan tampil seperti ini

![screenshot from 2017-11-11 10-10-17](https://user-images.githubusercontent.com/33483011/32685686-b42e8790-c6c8-11e7-901c-f1b97b2890e9.png)

**Comment by ad3n** [comment]
Menunya yang apa ya?

**Comment by j1top** [comment]
Alamat > Alamat Karyawan

atau sy Copy link address nya ini
http://127.0.0.1:8000/admin/?entity=EmployeeAddress&action=list&menuIndex=8&submenuIndex=1&sortField=createdAt&sortDirection=DESC

**Comment by ad3n** [comment]
noted

**Comment by ad3n** [comment]
@j1top apakah sudah fix dengan itu?

**Comment by j1top** [comment]
@ad3n ok
fixed

**Comment by j1top** [comment]
issue tambahan..
kalau alamat di isi lengkap sukses, tapi kalau field fax di kosongkan ada error seperti ini

![screenshot from 2017-11-11 10-31-39](https://user-images.githubusercontent.com/33483011/32685836-e162fbe4-c6cb-11e7-8e36-93fa600978b1.png)

**Comment by ad3n** [comment]
@j1top : ok done. bisa dicoba lagi
