### ISSUE TITLE
[Presensi] Download Template Absen No such file or directory

### ISSUE THREAD

**Issue by j1top** [KejawenLab/SemartHris#9]
![screenshot from 2017-11-11 13-37-21](https://user-images.githubusercontent.com/33483011/32687051-b4f07130-c6e5-11e7-9369-2b3137255f20.png)

**Comment by j1top** [comment]
error sama di menu lembur (download template Lembur) No such file or directory

![screenshot from 2017-11-11 13-40-23](https://user-images.githubusercontent.com/33483011/32687055-f59a4a26-c6e5-11e7-90ce-634f9ec8fa08.png)

**Comment by ad3n** [comment]
Ok noted... kayaknya ketinggalan di kantor hahaha

**Comment by ad3n** [comment]
Noted

**Comment by ad3n** [comment]
@j1top : done ya om, sudah saya upload :-D
